modLoader="javafml" #mandatory
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/Scouter456/Nether_Depths_Upgrade/issues"
[[mods]]
modId="netherdepthsupgrade" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Nether Depths Upgrade"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="soulsucker_logo.png" #optional
credits=""
authors="Scouter456"
description='''
This is a mod that gives the lava depths in the nether a little upgrade, credits for the fortress grouper and textures go to Crydigo
'''
[[dependencies.geckolib]]
modId="geckolib3"
mandatory=true
versionRange="[3.1.39,)"
ordering="BEFORE"
side="BOTH"
[[dependencies.netherdepthsupgrade]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"
[[dependencies.netherdepthsupgrade]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
